### ISSUE TITLE
Throws a deprecation notice with Doctrine ORM ^2.15

### ISSUE THREAD

**Issue by tonyaxo** [theofidry/AliceDataFixtures#263]
versions : * 1.7.0
doctrine/orm: 2.15.5

```bash
Subscribing to postConnect events is deprecated. Implement a middleware instead. (Connection.php:387 called by Connection.php:1654, https://github.com/doctrine/dbal/issues/5784, package doctrine/dbal)
Stack trace:
#0 [internal function]: Symfony\Bridge\PhpUnit\DeprecationErrorHandler->handleError(16384, 'Subscribing to ...', '/var/www/html/v...', 210)
#1 vendor/doctrine/dbal/src/Connection.php(387): Doctrine\Deprecations\Deprecation::trigger('doctrine/dbal', 'https://github....', 'Subscribing to ...', 'postConnect')
#2 vendor/doctrine/dbal/src/Connection.php(1654): Doctrine\DBAL\Connection->connect()
#3 vendor/doctrine/dbal/src/Connection.php(1185): Doctrine\DBAL\Connection->getWrappedConnection()
#4 [internal function]: Doctrine\DBAL\Connection->executeStatement('DELETE FROM sit...')
#5 vendor/doctrine/data-fixtures/src/Purger/ORMPurger.php(103): array_map(Array, Array)
#6 vendor/theofidry/alice-data-fixtures/src/Bridge/Doctrine/Purger/Purger.php(105): Doctrine\Common\DataFixtures\Purger\ORMPurger->purge()
```

**Comment by theofidry** [comment]
This bundle is not registering any event, so whilst it may be the trigger of this deprecation, I think it is because of the underlying code not the one from this bundle.
